language: node_js
env: TRAVISCI=true
node_js:
  - "0.10"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_install:
  - sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
  - npm install canvas
  - npm install karma-coffee-preprocessor karma-firefox-launcher

